language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester brunch
- bower install
- brunch build --env test
script:
- cd public_test && xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: zO+LoD389FzNjj2bA/vs+rkNr+4FE9vVq/PQTeu00rmQDX2mb4lE0sQ/3h5sqqClplAdP6zwUyQ0Jp0Joq7nAWKUSfd9GHIGYlDi1ro5GBHYlc83GIOwcGt+EehTSjA1WZm/+enVAXv9N56ic0zHbOL5Tdo/g7Eqr7fuGmUzPVpmSFja5dLt3Rlfc2JE7aItQah6pW0of/A3sy4wWW1h/vfyHV+jQ3394Wtu6nt6lCiYSQH1SNRBPLPPV1Lq7ICCNC5+v+s0xzIsJGYUM1KWJ6KUCWwnsilzasYoyat5mqR2las/rzcFJx1K9qtC75og6y2b8AjbXa6PPAYuMvfE1DbqhKq639HFrfX/jepCX5qfmwa2gVBA/kwDteLuijhnwW1dVaptCItEbA8h5WPTCWlWieNlb7BwEtguWCwks/dPZiLyCTll5ZmZBaGO9AZH8VVEHmLC11FYZTGD2oql2uPNuTUlGiiE0ooknHWadX9+C0lYcsiXBv/Cub1pDLT88PT1zNY3g4hR0i8wIopaCsPdjln2VzH0rADzV+plhcKZkz4C29LN7Hx73N0SqpXuUcWcloVQ+uDUs4M+GRz8f4VDtRjhepQJTqj0JlECCNYqAwaWSXsAWLYwxcBv3WjsrKMvBzycp3dH7ol+Cm22u6ybzaTCEcfiuw7iGMQxsks=
  - secure: UOnYZtC0QXLbARnBGy73UjrYTg3Z0QSvgY6XRLsrAGNn9YI5yxV5sBHT++wAFM8gWowkzLXQf4NYb72dUoHDW8aWn3GFJIghv/gZPAZoeHmcLbKNdcF/sEsbPEt8ztpya2zaBN5n5o/QOWCDOZ3gFfySNY6XsKPJZm22+E2ZKx2iyah2nVrkg5oGIqUnWSnP2hqdavbuk3e8SbvzWsPR2BeBGBlRMnD/DdCv3kt/E+xUsPU05vMGwzwpgkKBcBMDPxFpHiER0D0nEMbdydkh+dR7emjAUapTWacpWLGQZp3qGXAJG3tX5ecbhg0Z0hh3gAcro9ZUeR/AWjQKh1Q4qm20erVP211uAWKV9mmYizB8eiC9rg9oS5KR/pxstGdz9/N0150m3OAJlqQpfsEXIdH/OdBqDflJU7nVMw3VqFUi+Z+qMEhTRQ9EeO5qC4Iqk+MklmtVFZmpzVwNTn1vFVhBfV1Y0y2pLhj7Fsj5i3WXhD/O/VugCKomSv2Kb8ZxVn8NSwGSJAEYG7amBrb5TjWB/8MIZ3m9Tbfltbgz0agA6PH4hRbYZSqx5Ii283UnGGFeA5bjHpFOyS2ZM72bXEXb+X4lPXXoopSHkFlFh70DeDhYjyx8c5MvlrdnLQS85gzYLFdzXeQ+HeJsfOcWsGkisKdW5iP2SfbKf1xmxhg=
